# Generated by Django 6.0.7 on 2026-07-29 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_client_deal_dealcomment_deallog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('source_type', models.CharField(db_index=True, max_length=50)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('name_raw', models.CharField(blank=True, max_length=255)),
                ('phone_raw', models.CharField(blank=True, max_length=64)),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=32)),
                ('email_raw', models.EmailField(blank=True, max_length=254)),
                ('message_text', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_payload_json', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
                ('headers_json', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('duplicate', 'Duplicate'), ('processing', 'Processing'), ('processed', 'Processed'), ('suspicious', 'Suspicious'), ('retry_wait', 'Retry wait'), ('failed', 'Failed'), ('blocked', 'Blocked')], db_index=True, default='received', max_length=32)),
                ('ai_topic', models.CharField(blank=True, max_length=120)),
                ('ai_need', models.TextField(blank=True)),
                ('ai_urgency', models.CharField(blank=True, max_length=50)),
                ('ai_category', models.CharField(blank=True, max_length=50)),
                ('ai_spam_probability', models.FloatField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_suggested_reply', models.TextField(blank=True)),
                ('ai_suggested_department', models.CharField(blank=True, max_length=120)),
                ('risk_score_rules', models.PositiveSmallIntegerField(default=0)),
                ('risk_score_final', models.PositiveSmallIntegerField(default=0)),
                ('spam_reason', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_suggested_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggested_requests', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='intake.inboundrequest')),
                ('linked_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_requests', to='crm.client')),
                ('linked_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_requests', to='crm.deal')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='intake.inboundrequest')),
            ],
        ),
        migrations.CreateModel(
            name='IntakeThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('ip', 'IP'), ('global', 'Global')], max_length=16)),
                ('key', models.CharField(max_length=255)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'key', 'window_start'], name='intake_inta_scope_e023a0_idx')],
                'unique_together': {('scope', 'key', 'window_start')},
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('message', models.TextField(blank=True)),
                ('details_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inbound_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='intake.inboundrequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Blocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('kind', models.CharField(choices=[('phone', 'Phone'), ('ip', 'IP'), ('email_domain', 'Email domain')], db_index=True, max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocklist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'value'],
                'unique_together': {('value', 'kind')},
            },
        ),
        migrations.AddIndex(
            model_name='inboundrequest',
            index=models.Index(fields=['source_type', 'external_id'], name='intake_inbo_source__8c4f44_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundrequest',
            index=models.Index(fields=['status', 'next_retry_at'], name='intake_inbo_status_52f287_idx'),
        ),
    ]
