# Generated by Django 6.0.7 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0002_inboundrequest_ai_moderation"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundrequest",
            name="risk_restored_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
