# Generated by Django 6.0.7 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0003_inboundrequest_risk_restored_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundrequest",
            name="trust_level",
            field=models.CharField(
                choices=[("external", "External"), ("internal", "Internal")],
                db_index=True,
                default="external",
                max_length=16,
            ),
        ),
    ]
