# Generated by Django 6.0.7 on 2026-07-29 17:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.TextField(blank=True)),
                ('admin_chat_id', models.CharField(blank=True, max_length=64)),
                ('admin_telegram_ids', models.TextField(blank=True, help_text='Comma or newline separated numeric Telegram user ids.')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bot_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot settings',
                'verbose_name_plural': 'Bot settings',
            },
        ),
    ]
