# Generated by Django 6.0.7 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_client_deal_dealcomment_deallog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="is_spam",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
