# Generated by Django 6.0.7 on 2026-07-29 18:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_client_deal_dealcomment_deallog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('site', 'Сайт'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('other', 'Другой канал')], db_index=True, max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type', 'name', 'id'],
                'unique_together': {('type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_thread_id', models.CharField(max_length=255)),
                ('last_inbound_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dialogs', to='channels.channel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dialogs', to='crm.client')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='crm.deal')),
            ],
            options={
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Входящее'), ('outbound', 'Исходящее')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('received', 'Получено'), ('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки')], db_index=True, default='received', max_length=24)),
                ('text', models.TextField()),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('external_message_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channels.dialog')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_channel_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка')], db_index=True, max_length=16)),
                ('adapter', models.CharField(max_length=64)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='channels.message')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='dialog',
            index=models.Index(fields=['deal', 'last_message_at'], name='channels_di_deal_id_fb0410_idx'),
        ),
        migrations.AddIndex(
            model_name='dialog',
            index=models.Index(fields=['channel', 'external_thread_id'], name='channels_di_channel_d8d40f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dialog',
            unique_together={('channel', 'external_thread_id')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['dialog', 'created_at'], name='channels_me_dialog__a8ebbc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['direction', 'status'], name='channels_me_directi_c93e59_idx'),
        ),
    ]
