# Generated by Django 6.0.7 on 2026-07-29 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI')], default='ollama', max_length=16)),
                ('ollama_url', models.URLField(default='http://127.0.0.1:11434')),
                ('ollama_model', models.CharField(default='qwen3.5:9b', max_length=120)),
                ('openai_base_url', models.URLField(default='https://api.openai.com/v1')),
                ('openai_model', models.CharField(default='gpt-4.1-mini', max_length=120)),
                ('openai_api_key', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI settings',
                'verbose_name_plural': 'AI settings',
            },
        ),
    ]
