# Generated by Django 6.0.7 on 2026-07-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='openai_transcription_model',
            field=models.CharField(default='whisper-1', max_length=120),
        ),
    ]
