# Generated by Django 6.0.7 on 2026-07-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_update_openai_model_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='connection_type',
            field=models.CharField(choices=[('ollama', 'Ollama (локально)'), ('openai_official', 'OpenAI official'), ('openai_compatible', 'OpenAI-compatible (custom / bridge / proxy)')], default='ollama', max_length=32),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_check_message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_check_status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('ok', 'ok'), ('fail', 'fail')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='openai_api_style',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('chat_completions', 'Chat Completions'), ('responses', 'Responses')], default='chat_completions', max_length=32),
        ),
    ]
