# Generated by Django 6.0.7 on 2026-07-29 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aisettings_connection_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='name',
            field=models.CharField(default='Ollama локально', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='aisettings',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='ai_one_default_connection'),
        ),
    ]
